# Generated by Django 3.1.5 on 2021-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_datetime', models.DateTimeField(auto_now=True)),
                ('post_text', models.CharField(max_length=300)),
                ('post_image', models.ImageField(upload_to='post_images/')),
            ],
        ),
    ]
